# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4




# Para crear este archivo necesitas ir al directorio y abrir un cmd y usar """pyuic5 -x nameoffile.ui -o thisfile.py"""




# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.Boton1.setGeometry(QtCore.QRect(280, 330, 191, 51))
        self.Boton1.setObjectName("Boton1")
        self.etiqueta1 = QtWidgets.QLabel(self.centralwidget)
        self.etiqueta1.setGeometry(QtCore.QRect(280, 140, 201, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.etiqueta1.sizePolicy().hasHeightForWidth())
        self.etiqueta1.setSizePolicy(sizePolicy)
        self.etiqueta1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(21)
        font.setUnderline(True)
        self.etiqueta1.setFont(font)
        self.etiqueta1.setMouseTracking(True)
        self.etiqueta1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.etiqueta1.setTextFormat(QtCore.Qt.AutoText)
        self.etiqueta1.setAlignment(QtCore.Qt.AlignCenter)
        self.etiqueta1.setObjectName("etiqueta1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu1 = QtWidgets.QMenuBar(MainWindow)
        self.menu1.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menu1.setObjectName("menu1")
        self.menuAqui_se_abre_algo = QtWidgets.QMenu(self.menu1)
        self.menuAqui_se_abre_algo.setObjectName("menuAqui_se_abre_algo")
        MainWindow.setMenuBar(self.menu1)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu1.addAction(self.menuAqui_se_abre_algo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Boton1.setText(_translate("MainWindow", "Presioname"))
        self.etiqueta1.setText(_translate("MainWindow", "Hola Mundo!"))
        self.menuAqui_se_abre_algo.setTitle(_translate("MainWindow", "Aqui se abre algo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
